# Generated by Django 4.1.7 on 2023-04-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='safe',
            field=models.BooleanField(default=True),
        ),
    ]
